# Intro to Python and Data
In this overview we are going to walk through some basic principles of programming in python as well as exporing data.

# Numpy Arrays
High performance arrays written in C

In [1]:
import numpy as np

In [2]:
fixed_array = np.zeros((100,100), dtype=int)

In [3]:
fixed_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

## Working with Arrays

In [4]:
fixed_array[1]    # Select Single Row

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
fixed_array[1,2]   # Select Single Value at Row,Column

0

In [6]:
rand_array = np.random.rand(3,2)    # generate random values between 0 and 1 
rand_array                          # for array with 3 rows and 2 columns

array([[0.53751898, 0.29898055],
       [0.63104892, 0.86667857],
       [0.29978282, 0.18235668]])

# Loading Data
Data grabbed from, https://www.kaggle.com/tristan581/17k-apple-app-store-strategy-games


## Pandas Dataframes
Objects representing data tables with columns and transformation functions

> RESOURCE: useful [reference sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

<img src="https://cdn-images-1.medium.com/max/1600/1*JjZYjvyBurwgQa1RBRtzAA.png" style="width: 70%" />

# Creating a Dataframe

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame({"colA":[1,2,3], "colB":[4,5,6]})
df

colA  colB
0     1     4
1     2     5
2     3     6

# Importing Data

In [9]:
data = pd.read_csv("data/appstore_games.csv")

In [10]:
data.head(3)

URL         ID     Name  \
0   https://apps.apple.com/us/app/sudoku/id284921427  284921427   Sudoku   
1  https://apps.apple.com/us/app/reversi/id284926400  284926400  Reversi   
2  https://apps.apple.com/us/app/morocco/id284946595  284946595  Morocco   

  Subtitle                                           Icon URL  \
0      NaN  https://is2-ssl.mzstatic.com/image/thumb/Purpl...   
1      NaN  https://is4-ssl.mzstatic.com/image/thumb/Purpl...   
2      NaN  https://is5-ssl.mzstatic.com/image/thumb/Purpl...   

   Average User Rating  User Rating Count  Price In-app Purchases  \
0                  4.0             3553.0   2.99              NaN   
1                  3.5              284.0   1.99              NaN   
2                  3.0             8376.0   0.00              NaN   

                                         Description  \
0  Join over 21,000,000 of our fans and download ...   
1  The classic game of Reversi, also known as Oth...   
2  Play the classic strategy game Othello (also k...   

                  Developer Age Rating  \
0  Mighty Mighty Good Games         4+   
1          Kiss The Machine         4+   
2               Bayou Games         4+   

                                           Languages        Size  \
0  DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...  15853568.0   
1                                                 EN  12328960.0   
2                                                 EN    674816.0   

  Primary Genre                   Genres Original Release Date  \
0         Games  Games, Strategy, Puzzle            11/07/2008   
1         Games   Games, Strategy, Board            11/07/2008   
2         Games   Games, Board, Strategy            11/07/2008   

  Current Version Release Date  
0                   30/05/2017  
1                   17/05/2018  
2                    5/09/2017

In [11]:
data.tail(3)

URL          ID  \
17004  https://apps.apple.com/us/app/rabbit-vs-tortoi...  1474962324   
17005  https://apps.apple.com/us/app/fatall/id1474963671  1474963671   
17006  https://apps.apple.com/us/app/the-three-kingdo...  1475076711   

                           Name          Subtitle  \
17004        Rabbit Vs Tortoise               NaN   
17005                    FaTaLL  Most fun game!!!   
17006  The Three Kingdoms :Bomb               NaN   

                                                Icon URL  Average User Rating  \
17004  https://is2-ssl.mzstatic.com/image/thumb/Purpl...                  NaN   
17005  https://is1-ssl.mzstatic.com/image/thumb/Purpl...                  NaN   
17006  https://is1-ssl.mzstatic.com/image/thumb/Purpl...                  NaN   

       User Rating Count  Price   In-app Purchases  \
17004                NaN    0.0                NaN   
17005                NaN    0.0  9.99, 49.99, 3.99   
17006                NaN    0.0                NaN   

                                             Description      Developer  \
17004  "Rabbit Vs Tortoise is chess type cool simple ...  Vishal Baldha   
17005  Upgrade your character and use your skills to ...   Tayrem Games   
17006  The protagonist uses the method of placing a b...   ming bo tang   

      Age Rating Languages         Size Primary Genre  \
17004         4+        EN   23207936.0         Games   
17005         4+        EN  196750336.0         Games   
17006         4+    EN, ZH   22952960.0         Games   

                        Genres Original Release Date  \
17004          Games, Strategy             3/08/2019   
17005  Games, Strategy, Action             1/08/2019   
17006  Games, Strategy, Puzzle             2/08/2019   

      Current Version Release Date  
17004                    3/08/2019  
17005                    1/08/2019  
17006                    2/08/2019

In [12]:
data.describe()

ID  Average User Rating  User Rating Count         Price  \
count  1.700700e+04          7561.000000       7.561000e+03  16983.000000   
mean   1.059614e+09             4.060905       3.306531e+03      0.813419   
std    2.999676e+08             0.751428       4.232256e+04      7.835732   
min    2.849214e+08             1.000000       5.000000e+00      0.000000   
25%    8.996543e+08             3.500000       1.200000e+01      0.000000   
50%    1.112286e+09             4.500000       4.600000e+01      0.000000   
75%    1.286983e+09             4.500000       3.090000e+02      0.000000   
max    1.475077e+09             5.000000       3.032734e+06    179.990000   

               Size  
count  1.700600e+04  
mean   1.157064e+08  
std    2.036477e+08  
min    5.132800e+04  
25%    2.295014e+07  
50%    5.676895e+07  
75%    1.330271e+08  
max    4.005591e+09

# Working With Data

In [13]:
### Selecting a Column ###
data['Price'].head()

0    2.99
1    1.99
2    0.00
3    0.00
4    2.99
Name: Price, dtype: float64

In [14]:
### Selecting a Column With conditions ###
data['Price'][data.Price > 2].head(8)

0     2.99
4     2.99
26    2.99
29    2.99
30    2.99
32    5.99
33    7.99
35    2.99
Name: Price, dtype: float64